linters:
  enable:
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - typecheck
    - unused

run:
  timeout: 5m

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
